# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'KakaoTalk' do
 
 # Kakao module
pod 'KakaoSDKCommon'  # 필수 요소를 담은 공통 모듈
pod 'KakaoSDKAuth'  # 사용자 인증
pod 'KakaoSDKUser'  # 카카오 로그인, 사용자 관리
pod 'KakaoSDKTalk'  # 친구, 메시지(카카오톡)

 # Alamofire
pod 'Alamofire', '~> 5.2'

end
